services:
  - type: web
    name: ai-intern-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
    rootDir: backend

  - type: web
    name: ai-intern-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
    rootDir: frontend
